gamescollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'), #(1) use path, (2)define the path in the views file, (3)give it a name
    path('about/', views.about, name='about'),
    path('games/', views.games_index, name='index'),
    path('games/<int:game_id>/', views.games_detail, name='detail'),
    path('games/create', views.GameCreate.as_view(), name='games_create'),
    path('games/<int:pk>/update', views.GameUpdate.as_view(), name='games_update'), #class-based views force you to use PK
    path('games/<int:pk>/delete', views.GameDelete.as_view(), name='games_delete'),
    path('games/<int:game_id>/add_review', views.add_review, name='add_review'),
    path('games/<int:game_id>/assoc_player/<int:player_id>/', views.assoc_player, name='assoc_player'),
    path('games/<int:game_id>/unassoc_player/<int:player_id>/', views.unassoc_player, name='unassoc_player'),
    path('players/', views.PlayerList.as_view(), name='players_index'),
    path('players/<int:pk>/', views.PlayerDetail.as_view(), name='players_detail'),
    path('players/create/', views.PlayerCreate.as_view(), name='players_create'),
    path('players/<int:pk>/update/', views.PlayerUpdate.as_view(), name='players_update'),
    path('players/<int:pk>/delete/', views.PlayerDelete.as_view(), name='players_delete'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date

#define RATINGS tuple, with nested 2-tuples
RATINGS = (
    ('5', 'Excelent'),
    ('4', 'Great'),
    ('3', 'Average'),
    ('2', 'Okay'),
    ('1', 'Awful'),
)

# Create your models here.
class Player(models.Model):
    name = models.CharField(max_length=50)
    online = models.BooleanField(default=True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('players_detail', kwargs={'pk': self.id})
    


class Game(models.Model):
    name = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    release_date = models.DateField()
    description = models.TextField(max_length=300, default='')
    in_library = models.BooleanField(default=False)
    players = models.ManyToManyField(Player)

    def __str__(self):
        return f'Game is {self.name}, {self.release_date}'
    
# Automatically redirects to the game details page upon game creation
    def get_absolute_url(self):
        return reverse('detail', kwargs={'game_id': self.id})
    
# Detect if the game is hungry or not
    def fed_for_today(self):
        return self.feeding_set.filter(date=date.today()).count() >= len(RATINGS)   



class Review(models.Model):
    rating = models.CharField(max_length=1, choices = RATINGS, default = [2][0])
    title = models.CharField(max_length=100)
    review = models.TextField(max_length=250)
    date = models.DateField('posted on')

    #create a game_id FK, since Review belongs to Game
    game = models.ForeignKey(
        Game,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f"{self.get_rating_display()} - {self.title}: {self.review} - reviewed on {self.date}"
    
    class Meta: #a Meta class doesn't affect the class's structure
        ordering = ['-date'] #order indorfation in descending order by date

main_app/forms.py
from django.forms import ModelForm
from .models import Review

#ModelForms are used to generate inputs, to validate data of the submitted form and to create a model instance.
class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'title', 'review', 'date']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Game, Player
from .forms import ReviewForm


# games = [
#     {'name': 'The Witcher 3: Enhanced Edition', 'genre': 'RPG', 'release_date': '2015-05-15', 'in_library': True},
#     {'name': 'XCOM 2', 'genre': 'Strategy', 'release_date': '2016-02-05', 'in_library': True},
#     {'name': 'Total War: Three Kingdoms', 'genre': 'Strategy', 'release_date': '2019-05-23', 'in_library': True},
#     {'name': 'Stardew Valley', 'genre': 'Simulation', 'release_date': '2016-02-26', 'in_library': True},
#     {'name': 'Star Wars Jedi: Fallen Order', 'genre': 'Action-Adventure', 'release_date': '22019-11-15', 'in_library': True},
#     {'name': 'Elden Ring', 'genre': 'Souls-like', 'release_date': '2022-02-24', 'in_library': False},
#     {'name': 'Red-Dead Redemption 2', 'genre': 'Action-Adventure', 'release_date': '2019-12-05', 'in_library': False},
# ]

# Create your views here.
def home (request): #(4) define it in the views file. request is standard
    return render (request, 'home.html') #(5) render teh page upon request, send it to the html page in the 'templates' folder

def about (request):
    return render (request, 'about.html')

def games_index (request):
    games = Game.objects.all()
    return render (request, 'games/index.html', {
        'games': games,
    })

def games_detail (request, game_id):
    game = Game.objects.get(id=game_id)
    id_list = game.players.all().values_list('id')
    available_players = Player.objects.exclude(id__in=id_list)
    #instantiate ReviewForm to be rendered in detail.html
    review_form = ReviewForm()
    return render (request, 'games/detail.html', {
        'game': game,
        'review_form': review_form,
        'available_players': available_players,
    })

# Create a class to be applied to a specific model
class GameCreate(CreateView):
    model = Game
    fields = ['name', 'genre', 'release_date', 'description'] #displays only the name and age field in the form
    #fields = '__all__' #displays all field in the form

class GameUpdate(UpdateView):
    model = Game
    fields = '__all__'

class GameDelete(DeleteView):
    model = Game
    success_url = '/games'

def add_review(request, game_id):
    #create a ModelForm instance using the data that was submitted in the form
    form = ReviewForm(request.POST) #««« this is how te tell it that we will use the information passed on by the 'form' in the html
    #validate the form
    if form.is_valid():
        # We want a model instance, but we can't save to the database yet
        # because we have not yet assigned the game_id FK.
        new_review = form.save(commit=False)
        new_review.game_id = game_id
        new_review.save()
    return redirect('detail', game_id=game_id) #redirect takes advantage of the 'name' property in the routes, so we can use that instead of passing the entire route

class PlayerList(ListView):
    model = Player

class PlayerDetail(DetailView):
    model = Player

class PlayerCreate(CreateView):
    model = Player
    fields = '__all__'

class PlayerUpdate(UpdateView):
    model = Player
    fields = '__all__'

class PlayerDelete(DeleteView):
    model = Player
    success_url = '/players'

def assoc_player(request, game_id, player_id):
  Game.objects.get(id=game_id).players.add(player_id)
  return redirect('detail', game_id=game_id)

def unassoc_player(request, game_id, player_id):
  Game.objects.get(id=game_id).players.remove(player_id)
  return redirect('detail', game_id=game_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h2>About the Games Library</h2>
<hr>
<p>Games Library is a convenient collection of your favorite games from different gaming platforms!!</p>
<p>This app was developed by SEI-73 student Lucas Neno during a 2023 cohort</p>
<p>Join the Games Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Games Library</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
    <header class="navbar-fixed ">
        <nav>
            <div class="nav-wrapper #311b92 deep-purple darken-4">
                <ul>
                    <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Games Library</a></li>
                </ul>
                <ul class="right">
                    <li><a href="{% url 'about' %}">About</a></li>
                    <li><a href="{% url 'players_create' %}">+ Player</a></li>
                    <li><a href="{% url 'players_index' %}">View All Players</a></li>
                    <li><a href="{% url 'games_create' %}">+ Game</a></li>
                    <li><a href="{% url 'index' %}" class="allgamesbutton"><i class="material-icons">videogame_asset</i>All Games</a></li>
                </ul>
            </div>
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer class="page-footer #311b92 deep-purple darken-4">
        <div>
          All Rights Reserved, &copy; 2023 Games Library
        </div>
      </footer>
</body>
</html>

main_app/templates/games/detail.html
{% extends 'base.html'%}
{% block content %}

<h1>Game Detail</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content #3f51b5 indigo">
                <span class="card-title">{{ game.name }}</span>
                <p>Genre: {{ game.genre }}</p>
                <p>Release Date: {{ game.release_date }}</p>
                {% if game.in_library %}
                <p>In Library: Yes</p>
                {% else %}
                <p>In Library: No</p>
                {% endif %}
                <p>Description: {{ game.description }}</p>
            </div>
            <div class="card-action">
                <a href="{% url 'games_update' game.id %}">Edit</a>
                <a href="{% url 'games_delete' game.id %}">Delete</a>
            </div>
        </div>
    </div>

    <!-- Review Form -->
    <div class="col s6">
        <form action="{% url 'add_review' game.id %}" method="POST">
            {% csrf_token %}
            <!-- Render the inputs. Materialize doesn't display select inputs by default. They need tp be initialized using JavaScript.  Date also needs to be initialized  -->
            {{ review_form.as_p }}
            <input type="submit" class="btn" value="Add Review">
        </form>
        <br>
        <!-- Review View -->
        <table class="striped">
            <thead>
                <tr>
                    <th>Reviews</th>
                </tr>
            </thead>
            <tbody>
                {% for review in game.review_set.all %}
                <tr>
                    <p>{{review.get_rating_dispaly}} - {{review.title}}</p>
                    <p>{{review.review}}</p>
                    <p>{{review.date}}</p>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<hr>

<!-- Game's Players -->
<div class="row">
    <div class="col s6">
        <h3>{{ game.name }}'s Players</h3>
        {% if game.players.count %}
        {% for player in game.players.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    {{ player.name }} - Online:{{ player.online }}
                </span>
            </div>
            <div class="card-action">
                <form action="{% url 'unassoc_player' game.id player.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn">Remove</button>
                </form>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h5>No Players 😿</h5>
        {% endif %}
    </div>

    <!-- Available Players -->
    <div class="col s6">
        <h3>Choose a Player</h3>
        {% if available_players.count %}
        {% for player in available_players.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ player.name }} - Online:{{ player.online }}</span>
            </div>
            <div class="card-action">
                <form action="{% url 'assoc_player' game.id player.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn">Add</button>
                </form>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h5>No Players Available</h5>
        {% endif %}
    </div>

    <script>
        const dateEl = document.getElementById('id_date');
        M.Datepicker.init(dateEl, {
            format: 'yyyy-mm-dd',
            defaultDate: new Date(),
            setDefaultDate: true,
            autoClose: true
        });

        const selectEl = document.getElementById('id_rating');
        M.FormSelect.init(selectEl);

    </script>
    {% endblock %}

main_app/templates/games/index.html
{% extends 'base.html'%}

{% block content %}

<h1>Games Library</h1>

{% for game in games %}
<a href="{% url 'detail' game.id%}"><!-- <<<this helper funciton takes in the url's 'name' and then any arguments that relate to the urls, in order. In this example it associates 'game.id' to the reference '<int:cat_id>' seen in the urls.py -->
    <div class="card-panel teal">
        <div class="card-content white-text">
            <span class="card-title">{{ game.name }}</span>
            <p>Genre: {{ game.genre }}</p>
            <p>Release Date: {{ game.release_date }}</p>
            {% if game.in_library %}
            <p>In Library: Yes</p>
            {% else %}
            <p>In Library: No</p>
            {% endif %}
        </div>
    </div>
</a>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
    <h1>Home</h1>
{% endblock %}

main_app/templates/main_app/game_confirm_delete.html
{% extends 'base.html'%}
{% block content %}

<h1>Delete Game</h1>

<h4>Are sure you wnat to delete <span class="teal-text">{{ object.name }}</span>?</h4>

<!-- the action inf the form doesn't require any value, because an empty action applies the form to the URL in the paage it is in, and we are exploiting that property -->
<form action="" method="POST"> 
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' game.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/game_form.html
{% extends 'base.html' %}
{% block content %}

<!-- if there is some kind of context (information from the model) being uploaded, then object=True -->
{%if object %}
    <h1>Edit <span class="teal-text">{{ object.name }}</span></h1> 
    <!-- could also use {{ game.name }} -->
{%else%}
    <h1>Add Game</h1>
{%endif%}

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn">
</form>

{% endblock %}

main_app/templates/main_app/player_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Player</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'players_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/player_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Player Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ player.name }}</span>
        <p>Online: {{ player.online }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'players_update' player.id %}">Edit</a>
        <a href="{% url 'players_delete' player.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/player_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Player</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
        <!-- Render the inputs inside of <tr>s & <td>s -->
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
</form>

<script>
    const onlineBoolEl = document.getElementById('id_online');
    M.Checkbox.init(onlineBoolEl);
</script>

{% endblock %}

main_app/templates/main_app/player_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Player List</h1>

{% for player in player_list %}
  <a href="{% url 'players_detail' player.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ player.name }}</span>
            <p>Online: {{ player.online }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}